### ISSUE TITLE
10.10.4 is up, pls update

### ISSUE THREAD

**Issue by caotian** [toleda/wireless_half-mini#1]
10.10.4 is up, pls update

**Comment by toleda** [comment]
No changes, 10.10.4 working.

**Comment by toleda** [comment]
I was wrong, updated.

**Comment by RadwanMacSystem** [comment]
hello

i have a problem , with applehda892 , i use clover , 
the sound exist but the channel is wrong , 
how could i solve it , 
thank you 

Ahmed Radwan

**Comment by toleda** [comment]
Wrong repo.

**Comment by RadwanMacSystem** [comment]
I did and it work again , but i have different problem with installation of BCM Bluetooth card 94352 , i hope if you could help me .

**Comment by toleda** [comment]
See README, Problem Reporting
