### ISSUE TITLE
Support for BCM94350ZAE DW1820A?

### ISSUE THREAD

**Issue by neuhaus** [toleda/wireless_half-mini#11]
Is it possible/feasible to support eh BCM94350 with this driver? It's found on the DW1820A card that ships with the Dell XPS 13 9350.

**Comment by toleda** [comment]
Don't know. Try the 4352 solutions. Reply with injection method and IOReg.
Edit: 4350/device_id 43a3 is native.  Attach IOReg.

**Comment by neuhaus** [comment]
OK, I'm still waiting for the notebook to arrive.

**Comment by Khondlo** [comment]
Can BM93142 HM or AR9485WB-EG work with this injector?

**Comment by toleda** [comment]
Not supported, see README.

**Comment by Khondlo** [comment]
Ok, thanks a million

**Comment by mihun70** [comment]
Hello!
I have some serious problems regarding this wifi module...no working at all...
I have an Lenovo T460, tried all methods one by one all together.. reinstalling and started again with no results.
10.12.4 
[problem.zip](https://github.com/toleda/wireless_half-mini/files/966162/problem.zip)
Any help, suggestions is welcomed!

**Comment by toleda** [comment]
One method only; if a method doesn't work, installing all methods together always fails.
FakePCIID is not working, contact RehabMan.
Otherwise, remove FakePCIID and install the 4352 ssdt.

**Comment by mihun70** [comment]
[dsdt method.zip](https://github.com/toleda/wireless_half-mini/files/967765/dsdt.method.zip)
Removed fakepciid kexts, repatched dsdt with the arpt patch. On power on I get the panic from zip, at restart the os x is working but no wifi.

**Comment by holoto** [comment]
@neuhaus hello! have you test DW1820A?

**Comment by neuhaus** [comment]
No i haven't. Linux runs so great on this machine, i haven't felt inclined to try OS X

**Comment by holoto** [comment]
@neuhaus ok ,Thanks for the Reply
