### ISSUE TITLE
A2DP headphones on 10.12.1 ? bcm94352

### ISSUE THREAD

**Issue by vooze** [toleda/wireless_half-mini#14]
Hi

Thank you for all your hard work!

I have it 99% working (I think) I have followed your guide to setup BT and WiFi. WiFi works perfectly with both 2.4GHz and 5GHz, but Bluetooth are giving me some problems.

I'm testing it with Jaybird X2 headphones which is using A2DP profile, so they are a bit different to just a mouse or keyboard.

If I reboot and then connect to them, it's all good, but as soon as I switch to another audio source and try to switch back, I can't connect to them anymore. I even tried to unpair + pair, no success. It pairs and then disconnects.

Here is my config.plist: https://gist.github.com/vooze/abad75bcf0d7caccf7958afc3e273059

Do you notice something weird? I think I have all the things I should from 120-config.

The only thing I could not figure out was if I was supposed to change 81F952AA00006690 to something else if I'm on in US/FCC. Comment: 10.12-BCM94352-5GHz-US-FCC-darkvoid. I did change 4183FCFF742C48 to 66C706444BEB2B (DK, instead of US)

But I'm not sure if that even have anything to do with bluetooth, or if that is only for WiFi.

Thank you so much.

I really have no idea where to go from here.

The BT + Headset works in Windows, so it's not a hardware issue.

**Comment by toleda** [comment]
No mention of motherboard. BT issues are usually USB issues, XHCI specifically.  See README/BT Injection for USB links.

**Comment by vooze** [comment]
Okay strange, now it seems to be working, after removing kext files (BrcmFirmwareRepo.kext
BrcmPatchRAM2.kext) from Library/Extensions/ and installing to System/Library/Extensions/... Sorry for taking your time, and thank you again!
