### ISSUE TITLE
Can't get BCM94352/HMB working

### ISSUE THREAD

**Issue by jaredallard** [toleda/wireless_half-mini#17]
OS: 10.12.2

Here's the a barebones zip of clover setup. Bluetooth isn't important so I don't need to worry about that.
[CLOVER.zip](https://github.com/toleda/wireless_half-mini/files/677776/CLOVER.zip)

So far S/L/E has FakePCID/IntelHD/IntelHDMI (needed fro GPU) as well as the BluetoothPatchRAM2 BluetoothFirmware.

My guess is it's something to do with the clover config, or DSDT.

Here's some info from DPICManager

![PCI List](https://cloud.githubusercontent.com/assets/2391349/21553404/f249ebe2-cdbc-11e6-9c9b-20261078d6f2.png)
![Status](https://cloud.githubusercontent.com/assets/2391349/21553406/f48d1c26-cdbc-11e6-8e74-ee0746373175.png)

Please let me know if you need anything else!

**EDIT** `lspci -v`

```sh
08:00.0 Network controller: Broadcom Limited BCM4352 802.11ac Wireless Network Adapter (rev 03)
        Subsystem: AzureWave Device 2123
        Flags: bus master, fast devsel, latency 0, IRQ 18
        Memory at b2600000 (64-bit, non-prefetchable) [size=32K]
        Memory at b2400000 (64-bit, non-prefetchable) [size=2M]
        Capabilities: [48] Power Management version 3
        Capabilities: [58] MSI: Enable- Count=1/1 Maskable- 64bit+
        Capabilities: [68] Vendor Specific Information: Len=44 <?>
        Capabilities: [ac] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [13c] Device Serial Number 74-c6-00-ff-ff-00-00-01
        Capabilities: [150] Power Budgeting <?>
        Capabilities: [160] Virtual Channel
        Capabilities: [1b0] Latency Tolerance Reporting
        Capabilities: [220] #15
        Kernel driver in use: wl
        Kernel modules: bcma, wl
```

**Comment by toleda** [comment]
See README/Airport Injection Methods/Enable WiFi
Install one method.
If problems, see README/Problem Reporting; attach requested files

**Comment by jaredallard** [comment]
I've tried all of them individually, but non seem to work. I'll attach some logs soon

**Comment by toleda** [comment]
All work. Attach files.

**Comment by jaredallard** [comment]
Using the FakePCIID method.
Using 10.12.2

[IOREG.zip](https://github.com/toleda/wireless_half-mini/files/681277/IOREG.zip)

Screenshots:
  i. see original post.
  ii. ![screen shot 2017-01-02 at 11 04 25](https://cloud.githubusercontent.com/assets/2391349/21594765/44e7bade-d0db-11e6-98d4-d1e73564ab46.png)

Boot Log:

[BOOTLOG.zip](https://github.com/toleda/wireless_half-mini/files/681280/BOOTLOG.zip)

Toolset:

[TOOLSET.acpi.zip](https://github.com/toleda/wireless_half-mini/files/681281/TOOLSET.acpi.zip)

Clover:

Config: see original post (CLOVER.zip)

[DSDT-backlight.zip](https://github.com/toleda/wireless_half-mini/files/681284/DSDT-backlight.zip)

That should be basically everything asked for in problem reporting, minus irrelevant files (cmd line, chameleon, etc)

Thanks a lot.

**Comment by ArsBinarii** [comment]
same here.
14e4:43b1 - no method works (situated at RP03)
The only strange way is that using FakePCIID way FakePCIID_Broadcom_WiFi.kext will not load.
The last thing I tried is SSDT inject of _SB.PCI0.RP03.PXSX._DSM to no success.

I will try to mod the original Kext with the 14e4:43b1 and will let you know but that just seems dirty

**Comment by jaredallard** [comment]
@rrprime Let me know if anything works!  I've had to resort to USB tethering my phone and using it as wifi for now :(

**Comment by ArsBinarii** [comment]
@jaredallard  always have a usb wifi card as a backup https://www.amazon.com/Realtek-RTL8188EU-Wireless-802-11n-Network/dp/B00L28AN88 you can find them at maybe $2 on aliexpress. they work on 10.12.2 with the D-Link DWA-131 MacOSX driver.

Will try tonight to mod the original kext's plist to add the 14e4:43b1 and will let you know

**Comment by jaredallard** [comment]
@RRPRIME Find out anything? 🤞

**Comment by ArsBinarii** [comment]
nothing yet, but I booted my desktop and found I was using the toledaARP.kext on 10.10 to get the BCM going. I modified the plist and added my id in there but no luck. I ended up erasing the whole SSD for another action. I need to reinstall Sierra and see how can I find a way to fix this on 10.12.2. I will post here as soon as I have news

**Comment by toleda** [comment]
Apologize for the delay in replying
@RRPRIME 
Files show FakePCIID is not working, remove
Try https://github.com/toleda/wireless_half-mini/blob/master/ssdt_arpt/ssdt_arpt-rp03-bcm4352.zip
toledaARP.kext is deprecated, remove.
Reply with new files

**Comment by jaredallard** [comment]
@toleda By files, you mean regarding mine, correct? Because if so, I can't remove FakePCIID, it's needed for my GPU.

**Comment by ArsBinarii** [comment]
@toleda yeah that was my next idea. The unit I was speaking of was my laptop and I noticed that my old desktop install was using your old toledaARP.kext. I am literally reinstalling now the Sierra 10 .12.2 (wanted a clean install) and will post the results and files if needed.

**Comment by ArsBinarii** [comment]
Semi good news: used the ssdt_arpt-rp03-bcm4352.aml now the device is compatible with 14e4:43a0 which is good news see attached file, even more 
   59    0 0xffffff7f81a39000 0x7bd000   0x7bd000   com.apple.driver.AirPort.Brcm4360 (1100.37.1a16) C7639630-B474-3DAD-BD3E-8BEE4D0D1706 <58 57 56 51 12 7 6 5 4 3 1>
Is loaded.

Now the bad part I can't see the device in System information so no dice.....

[prime’s MacBook Air.zip](https://github.com/toleda/wireless_half-mini/files/720750/prime.s.MacBook.Air.zip)

**Comment by toleda** [comment]
@RRPRIME: The ssdt is working.  Attach all Problem Reporting files.  Does your laptop have a WiFi whitelist?
@jaredallard: Remove the FakePCIID_wifi... kext only.

**Comment by jaredallard** [comment]
@toleda OK, so I removed the wifi kext and instead inserted (without modification) the SSDT into ACPI/patch/SSDT.aml

Log shows it's inserting the SSDT but nothing has changed. Need new files?

**Comment by ArsBinarii** [comment]
@toleda 
[Archive.zip](https://github.com/toleda/wireless_half-mini/files/721478/Archive.zip) - Hope all the files are here

The card works perfectly in windows 10...

**Comment by ArsBinarii** [comment]
2017-01-22 02:00:50.181450+0100 0xe8       Default     0x0                  0      kernel: (AirPortBrcm4360) ARPT: 1.821323: srom rev:11
2017-01-22 02:00:50.291885+0100 0xe8       Default     0x0                  0      kernel: (AirPortBrcm4360) ARPT: 1.931757: wlcStart failed
2017-01-22 02:00:50.305910+0100 0xe8       Default     0x0                  0      kernel: (AirPortBrcm4360) ARPT: 1.945784: AirPort_Brcm43XX::start: failed
2017-01-22 02:00:50.306116+0100 0xe8       Default     0x0                  0      kernel: (AirPortBrcm4360) ARPT: 1.945990: Memory leak of bytes 1192
2017-01-22 02:00:50.313359+0100 0xe8       Default     0x0                  0      kernel: (AirPortBrcm4360) ARPT: 1.953233: AirPort_Brcm43XX::start: Failed 'startGated()'

**Comment by ArsBinarii** [comment]
@toleda At this point I am starting to "blame" the card and the firmware it has....Tried a BCM4322 and if worked so I can rule out the SSDT patching....so it is either something inside the AirPortBrcm4360 that crashes with the CE123H or the card just does not play nice with OS X at all.

Not sure if this is fixable....on the top of my head maybe try a 10.10 or 10.11 install or get AirPortBrcm4360 from those versions and see if it behaves the same.

Or the AirPortBrcm4360 is not expected on the MAcAir6,2 so I might try whitelisting the board-id

**Comment by ArsBinarii** [comment]
@jaredallard After the SSDT isntall fire up a terminal and sudo su (not sure if it is necessary)  and:
 log show | grep "AirPortBrcm4360" 
post the last 10-15 lines reported by log show. Also it might be worth checking of the AirPortBrcm4360 kext loads: 
kextstat status | grep "Brcm"

**Comment by jaredallard** [comment]
```bash
2017-01-12 23:43:19.524120-0800 0xd1       Default     0x0                  0      kernel: (AirPortBrcm4360) ARPT: 0.883303: AirPort_Brcm43XX:probe:, this[0xc2ca8b28d5dabbd1]  score[1110]
2017-01-12 23:43:20.174154-0800 0xd1       Default     0x0                  0      kernel: (AirPortBrcm4360) ARPT: 1.533337: srom rev:11
2017-01-12 23:43:20.283709-0800 0xd1       Default     0x0                  0      kernel: (AirPortBrcm4360) ARPT: 1.642892: wlcStart failed
2017-01-12 23:43:20.283717-0800 0xd1       Default     0x0                  0      kernel: (AirPortBrcm4360) ARPT: 1.642901: AirPort_Brcm43XX::start: failed
2017-01-12 23:43:20.283753-0800 0xd1       Default     0x0                  0      kernel: (AirPortBrcm4360) ARPT: 1.642938: Memory leak of bytes 1192
2017-01-12 23:43:20.283768-0800 0xd1       Default     0x0                  0      kernel: (AirPortBrcm4360) ARPT: 1.642952: AirPort_Brcm43XX::start: Failed 'startGated()'
```

This is repeated over and over with `log show | grep "AirPortBrcm4360"`

`kextstat | grep "Brcm"`

```bash
  111    1 0xffffff7f821d0000 0x6000     0x6000     com.no-one.BrcmFirmwareStore (2.2.7) FA907595-C1CB-3D88-AD98-ADCDA9F29625 <5 4 3>
  112    0 0xffffff7f821d6000 0x6000     0x6000     com.no-one.BrcmPatchRAM2 (2.2.7) 76FC3024-9FF8-3607-A616-DF7C550751CB <111 20 5 4 3 1>
```

**Comment by ArsBinarii** [comment]
@jaredallard yeah, apparently you have the same issue as I'm having....couldn't get much info on the  wlcStart failed though....but what is weird is that your kext for wifi is not loading at all so at this point your card is not recognized. On the 2017-01-12 the kext was loading but you are still stuck even if you do get your kext to load.

**Comment by jaredallard** [comment]
This sounds like bad news. https://www.tonymacx86.com/threads/rebranding-make-bcm943162zp-m-2-ngff-to-work-with-yosemite.157086/page-3

**Comment by ArsBinarii** [comment]
I looked over that just speculations...mostly nobody went into much details about what is going on......

**Comment by jaredallard** [comment]
@RRPRIME Very true, however, it does sound like something with our hardware is off with the latest update.

**Comment by ArsBinarii** [comment]
welll.....not really sure....I have a 10.9 on my desktop so I might pop the card in and see if I can get the 4352 to work in 10.9. is by any chance your card a rev05 (see back of the card) ?

**Comment by RRPRIME** [comment]
Confirmed working on 10.9 with toledaARP.kext .. when I have the time I will do some dumps

![screen shot 2017-01-23 at 12 25 37 am](https://cloud.githubusercontent.com/assets/6293391/22186697/9900a068-e102-11e6-85d9-3cd51269ca82.png)

Will try to install 10.10 and 10.11 to see when it started failing and extract ioregs and DSDTs and kexts....

**Comment by ArsBinarii** [comment]
Confirmed working on 10.9 with toledaARP.kext .. when I have the time I will do some dumps

Will try to install 10.10 and 10.11 to see when it started failing and extract ioregs and DSDTs and kexts....

![screen shot 2017-01-23 at 12 25 37 am](https://cloud.githubusercontent.com/assets/6293391/22186729/1b20387e-e103-11e6-9546-5636236183b6.png)

**Comment by ArsBinarii** [comment]
@jaredallard - were you using 10.12.1 or 10.12.0 before and the card was working ?

**Comment by jaredallard** [comment]
I wasn't using any version before. I'm honestly considering ditching this on Mac OSX in general because I get poor performance with this card on linux as opposed to my Intel card I had before, and the usb wifi I have right now is OK enough.

**Comment by toleda** [comment]
@RRPRIME 
Archive, same.

**Comment by ArsBinarii** [comment]
[10.9.zip](https://github.com/toleda/wireless_half-mini/files/727678/10.9.zip) will come back with 10.10 and 10.11 and 10.12 since this is a new setup

**Comment by toleda** [comment]
Remove toledaARP.kext, install https://github.com/toleda/wireless_half-mini/blob/master/ssdt_arpt/ssdt_arpt-rp02-bcm4352.zip
Confirm 10.9/WiFi working, reply with new files.
Proceed with newer OSs

**Comment by ArsBinarii** [comment]
ssdt_arpt-rp02-bcm4352.zip contains SSDT-ARPT-RP03-4352.aml
made modifications for RP02

**Comment by ArsBinarii** [comment]
10.9.4
[10_9_AirPortBrcm4360.kext_included.zip](https://github.com/toleda/wireless_half-mini/files/730582/10_9_AirPortBrcm4360.kext_included.zip)

**Comment by ArsBinarii** [comment]
10.12.2
[10_12_AirPortBrcm4360.kext_included.zip](https://github.com/toleda/wireless_half-mini/files/730595/10_12_AirPortBrcm4360.kext_included.zip)

**Comment by toleda** [comment]
@RRPRIME
My mistake, rp02 fixed
10.12: patch missing, see README/BCM94352 5 GHz/Handoff Patch (10.12+)
WiFi: 5 GHz patch mandatory, other 2 optional.
Reply with new IOReg.

**Comment by ArsBinarii** [comment]
@toleda - I erased the 10_12 partition but will re-do it, not sure how the handoff to 5Ghz affects the init of the device but if it helps debugging the issue I am happy to do it. Will get to this during the weekend.

**Comment by toleda** [comment]
Handoff and 5 GHz are different patches. 5 GHz patch is different for MacOS version.

**Comment by RRPRIME** [comment]
had a bit of a problem with the old MacOS and the certificates
[10_11_AirPortBrcm4360.zip](https://github.com/toleda/wireless_half-mini/files/736584/10_11_AirPortBrcm4360.zip)

**Comment by RRPRIME** [comment]
had a bit of a problem with the old MacOS and the certificates
[10_11_AirPortBrcm4360.kext_included.zip](https://github.com/toleda/wireless_half-mini/files/736585/10_11_AirPortBrcm4360.kext_included.zip)

**Comment by ArsBinarii** [comment]
had a bit of a problem with the old MacOS and the certificates
10.10
[10_10_AirPortBrcm4360.kext_included.zip](https://github.com/toleda/wireless_half-mini/files/736586/10_10_AirPortBrcm4360.kext_included.zip)

**Comment by toleda** [comment]
10.10 WiFi working, BT is not.
"had a bit of a problem with the old MacOS and the certificates" ???  Clarify

**Comment by ArsBinarii** [comment]
hey working on 10.11 now. I know about BT, I did not apply the Rehab kexts. 

10.10 Yosemite was failing during install on the certificate checking after googling a bit I had to turn back the time on the machine to 28 Jan 2016 to get it to install.

PS: 10.11.4 - clover 5GHZ Kext patch is not working had to run the command

**Comment by ArsBinarii** [comment]
10.11.4 - 5Ghz patch via command - wifi working
[10_11_AirPortBrcm4360.kext_included.zip](https://github.com/toleda/wireless_half-mini/files/736642/10_11_AirPortBrcm4360.kext_included.zip)

**Comment by ArsBinarii** [comment]
10.11.4 - with Clover patches - 5ghz not working also what is weird is that the find and replace are the same beside the country code, tried at first with the correct country code and after US still nothing

[10_11_AirPortBrcm4360.zip](https://github.com/toleda/wireless_half-mini/files/736645/10_11_AirPortBrcm4360.zip)

The find and replace in the command seems to be the same as the clover patch...hmm...a bit weird

**Comment by toleda** [comment]
script and clover patch make the same edits. Fixed a comment typo in the .plist (no functional difference).

**Comment by ArsBinarii** [comment]
@toleda hey, sorry I was busy fixing a macbook air (some waterdamage). 
Is is working on 10.12 I was **missing the-darkvoid patch**...I feel like a fool....
![screen shot 2017-01-28 at 10 53 55 pm](https://cloud.githubusercontent.com/assets/6293391/22400113/b645642a-e5ac-11e6-99f0-2abc05bdc765.png)

Can be closed. I guess I will be going back to patching the VGA connector in the framebuffer on 10.12...

**Comment by ArsBinarii** [comment]
@jaredallard - I was missing the-darkvoid patch download:
[Clover patches](https://github.com/toleda/wireless_half-mini/blob/master/config-bcm94352-120.plist.zip)
enable the the-darkvoid patch

**Comment by jaredallard** [comment]
@RRPRIME Cool! When I get my kit to re-install the device into my laptop I'll give this all a shot!

Honestly this arose from the very confusing documentation that is the README, would be cool if it was a bit more formatted and explained better.

**Comment by jaredallard** [comment]
So I'm still unable to get this to work. I think it has to do with FakePCIID having to be used on my system.

**Comment by jaredallard** [comment]
So AddDGTP and Fix_Airport had to be disabled for Clover to not black screen for me. I also selectively choose which patches to include. It works now! :)
