### ISSUE TITLE
My Bluetooth can't be loaded on startup and the screen flush very quickly. here is the picture.

### ISSUE THREAD

**Issue by goxofy** [toleda/wireless_half-mini#18]
my device is bcm94360hmb and I used the BrcmPatchRAM2.kext and BrcmFirmwareRepo.kext in /S/L/E. It works well on 10.11+ but can't work on 10.12.2.

[0b05:180a] Azurewave (4360/20702 combo)

here is the screen output

http://i1.piimg.com/4851/fd238d44ed725674.jpg

Thanks

**Comment by toleda** [comment]
Apologize for the delay.
Attach all README/Problem Reporting files
