### ISSUE TITLE
Syntax Error in wireless_bcm94352-110-v4.0a-command

### ISSUE THREAD

**Issue by RWejlgaard** [toleda/wireless_half-mini#2]
There was a syntax error in the if statement from line 249 to 317. Fixed by changing 'thena' to 'then' on line 249.

**Comment by toleda** [comment]
Missed your post.  Fixed in 4.0b.  Thanks.

**Comment by RadwanMacSystem** [comment]
I already setup El Capitan and install wifi and the Bluetooth but the mouse and keyboard which are Apple original in switch between connect and disconnect
I do not know how to solve it

**Comment by toleda** [comment]
USB problem. 10.11/USB must be conjured correctly.  Off topic.
