### ISSUE TITLE
BCM94352 (CE123H) 5GHz not working

### ISSUE THREAD

**Issue by dennis97519** [toleda/wireless_half-mini#26]
Using rehabman's fakepciid v20171215, and the 10.11-BCM94352-5GHz-US-FCC-dv patch
```
  System Version:	OS X 10.11.6 (15G20015)
  Software Versions:
  CoreWLAN:	11.0 (1101.20)
  CoreWLANKit:	11.0 (1101.20)
  Menu Extra:	11.0 (1121.34.2)
  System Information:	12.0 (1100.2)
  IO80211 Family:	11.1 (1110.26)
  Diagnostics:	5.1 (510.88)
  AirPort Utility:	6.3.6 (636.5)

  Interfaces:
en0:
  Card Type:	AirPort Extreme  (0x14E4, 0x2123)
  Firmware Version:	Broadcom BCM43xx 1.0 (7.21.95.178.1a2)
  MAC Address:	(derp)
  Locale:	Unknown
  Country Code:	XT
  Supported PHY Modes:	802.11 a/b/g/n/ac
  Supported Channels:	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14
  Wake On Wireless:	Supported
  AirDrop:	Supported, Channel 0
  Status:	Connected
```

**Comment by toleda** [comment]
Attach IOReg and config.plist

**Comment by dennis97519** [comment]
Thanks for the fast reply. Attached.
[ioregconfig.zip](https://github.com/toleda/wireless_half-mini/files/1866045/ioregconfig.zip)

**Comment by toleda** [comment]
Attach Clover boot log.

**Comment by dennis97519** [comment]
there you go
[bootlog.txt](https://github.com/toleda/wireless_half-mini/files/1866057/bootlog.txt)

**Comment by toleda** [comment]
Do not see anything wrong.
Did 5 GHz work previously?
If yes, what changed?

**Comment by dennis97519** [comment]
5GHz also not working previously...
Is it something with the locale and country code?

**Comment by dennis97519** [comment]
I used to be using a BCM94360 native apple wifi card with an adapter though, but I needed a 50cm ribbon cable to route the PCIe connection, which I think made the internet connection really slow, so I changed to this.

**Comment by toleda** [comment]
Clover_v4305 and newer require updated kext patches.  Download config-bcm94352-130.plist and update Name for the 5 GHz patch.

**Comment by dennis97519** [comment]
Ah I see... Clover now requires full identifier for the kext patches.
It is now working. Thank you very much.
